### ISSUE TITLE
Kjøre prosjekter lokalt

### ISSUE THREAD

**Issue by OleksandrChmyrNAV** [navikt/ebxml-processor#54]
I https://github.com/navikt/ytelser-rest-proxy/blob/main/src/test/java/DevMain.java
finnes det en mekanisme som gjør det mulig å kjøre prosjektet lokalt ved (overraskelse) å stjele miljø variabler fra kjørende pod i Kubernetes.
Jeg foreslår å undersøke denne løsningen og (hvis det er mulig) bruke den i andre prosjektene.
Det kan bli veldig nyttig nå at vi er flere mens dev-miljø  er fortsatt ett.

**Comment by OleksandrChmyrNAV** [comment]
I passiv utvikling.

**Comment by RettIProd** [comment]
Oppgaven er riktig utført men etter vurdering så vil dette gjøre det "for enkelt" / terskelen senkes betraktelig for å hente ut secrets og variabler som egentlig ikke skal hentes ut.

Det holder med at vi har muligheten til å gjøre dette ved behov evt. kan vi se an hvorvidt denne problemstillingen oppstår igjen.
Setter denne til "Done" uten merge, enn så lenge kan vi ha dette i bakhånd. 🙂
